apiVersion: v1
kind: ConfigMap
metadata:
  name: file-queue-config
data:
  INPUT_FILE: "{{ .Values.config.inputFile }}"
  OUTPUT_FILE: "{{ .Values.config.outputFile }}"
  AMQP_URL: "{{ .Values.config.amqpUrl }}"

