apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  selector:
    app: consumer
  ports:
    - name: metrics
      port: {{ .Values.consumer.port }}
      targetPort: {{ .Values.consumer.port }}

