apiVersion: v1
kind: Service
metadata:
  name: producer
  labels:
    app: producer
spec:
  selector:
    app: producer
  ports:
    - name: metrics
      port: {{ .Values.producer.port }}
      targetPort: {{ .Values.producer.port }}

