{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: producer-monitor
  labels:
    release: {{ .Values.monitoring.releaseLabel }}
    app: producer
spec:
  selector:
    matchLabels:
      app: producer
  endpoints:
    - port: metrics
      path: /metrics/

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: consumer-monitor
  labels:
    release: {{ .Values.monitoring.releaseLabel }}
    app: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  endpoints:
    - port: metrics
      path: /metrics/
{{- end }}
