{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: producer-monitor
spec:
  selector:
    matchLabels:
      app: producer
  endpoints:
    - port: "{{ .Values.producer.port }}"
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: consumer-monitor
spec:
  selector:
    matchLabels:
      app: consumer
  endpoints:
    - port: "{{ .Values.consumer.port }}"
      path: /metrics
{{- end }}

