apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc
spec:
  accessModes:
    # Not supported by k3d
    # - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.sharedVolume.size }}"

